/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package typespeed;
import typespeed.view.TypespeedGUI;

public class App {
    public static void main(String[] args) {
        TypespeedGUI game = new TypespeedGUI(); 
        game.displayWord("hello");
        game.displayWord("word");
    }
}
