/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package typespeed; 
import typespeed.model.GameModel; 
import typespeed.model.Word; 
import typespeed.model.Difficulty; 

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList; 

public class GameModelTest {
    @Test
    public void testStartGame(){
        GameModel gameModel = new GameModel(new ArrayList<>(), Difficulty.EASY);

        gameModel.startGame(); 

        assertEquals(60, gameModel.getGameTime());
        assertEquals(0, gameModel.getScore());
        assertEquals(0, gameModel.getMissedWordsCount());
        assertEquals(0, gameModel.getWords().size());

    }

    @Test
    public void testIsGameOver(){
        GameModel gameModel = new GameModel(new ArrayList<>(), Difficulty.EASY);

        gameModel.setGameTime(10);
        assertFalse(gameModel.isGameOver());

        gameModel.setGameTime(0);
        assertTrue(gameModel.isGameOver());
    }

    @Test 
    public void testAdjustWordBasedOnDifficulty(){
        Word word = new Word("Test"); 

        GameModel easyModel = new GameModel(new ArrayList<>(), Difficulty.EASY);
        GameModel mediumModel = new GameModel(new ArrayList<>(), Difficulty.MEDIUM);
        GameModel hardModel = new GameModel(new ArrayList<>(), Difficulty.HARD);

        easyModel.adjustWordBasedOnDifficulty(word);
        assertEquals(10, word.getSpeed());

        mediumModel.adjustWordBasedOnDifficulty(word);
        assertEquals(10, word.getSpeed());

        hardModel.adjustWordBasedOnDifficulty(word);
        assertEquals(15, word.getSpeed());
    }
}
