/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package typespeed; 
import typespeed.model.GameModel; 
import typespeed.model.Word; 

import java.util.ArrayList; 
import java.util.List; 

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Before;

public class GameModelTest {
    private GameModel gameModel; 
    private List<String> wordList; 

    @Before
    public void setUp(){
        wordList = new ArrayList<>(); 
        wordList.add("apple");
        wordList.add("banana");

        gameModel = new GameModel(wordList);
    }

    @Test
    public void testGameStartAndEnd(){
        gameModel.startGame();
        assertEquals(60, gameModel.getGameTime());
        assertEquals(0, gameModel.getScore());
        assertFalse(gameModel.isGameOver());

        while(!gameModel.isGameOver()){
            gameModel.generateWord(); 
            gameModel.moveWords(); 
        }
        gameModel.endGame();
        assertTrue(gameModel.isGameOver());
    }

    @Test
    public void testWordGeneration(){
        gameModel.startGame(); 

        int initialWordsCount = gameModel.getWords().size();
        gameModel.generateWord();
        int updatedWordsCount = gameModel.getWords().size(); 

        assertTrue(updatedWordsCount > initialWordsCount); 
    }
}
